/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PA1_P2_TAREA2_DARWIN_ROMERO;
import javax.swing.table.DefaultTableModel;
import PA1_P2_TAREA2_DARWIN_ROMERO.IngresarUsuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_MOSTRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_TABLES = new javax.swing.JTable();
        JB_REGISTRO = new javax.swing.JButton();
        JB_ELIMINAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXT_MOSTRAR = new javax.swing.JTextField();
        JB_EDITAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JB_MOSTRAR.setText("MOSTRAR");
        JB_MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_MOSTRARActionPerformed(evt);
            }
        });

        JT_TABLES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nombre", "apellido", "peso", "sexo", "departamento", "municipio"
            }
        ));
        JT_TABLES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_TABLESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JT_TABLES);

        JB_REGISTRO.setText("REGISTRO");
        JB_REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_REGISTROActionPerformed(evt);
            }
        });

        JB_ELIMINAR.setText("ELIMINAR");
        JB_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ELIMINARActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        JB_EDITAR.setText("EDITAR");
        JB_EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EDITARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(TXT_MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(JB_MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(JB_REGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(JB_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(JB_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(TXT_MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JB_REGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JB_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JB_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_MOSTRARActionPerformed
   Statement Sentencia;
        ResultSet rsDatos;
       String SQL = "SELECT * FROM HUMANO";
       int Fila = 0;
       DefaultTableModel modelo;
       modelo = (DefaultTableModel) JT_TABLES.getModel();
       modelo.setNumRows(0);
       try{
           Sentencia = PRINCIPAL_CONECCION.Conexion.createStatement();
           rsDatos = Sentencia.executeQuery(SQL);
           while(rsDatos.next()){
              modelo.addRow(new Object []{});
              JT_TABLES.setValueAt(rsDatos.getString("ID"), Fila, 0);  
              JT_TABLES.setValueAt(rsDatos.getString("NOMBRE"), Fila, 1);
              JT_TABLES.setValueAt(rsDatos.getString("APELLIDO"), Fila, 2);
              JT_TABLES.setValueAt(rsDatos.getString("PESO"), Fila, 3); 
              JT_TABLES.setValueAt(rsDatos.getString("SEXO"), Fila, 4);
              JT_TABLES.setValueAt(rsDatos.getString("DEPARTAMENTO"), Fila, 5);   
              JT_TABLES.setValueAt(rsDatos.getString("MUNICIPIO"), Fila, 6);
              Fila++;
  
              
   }
        rsDatos.close();
         Sentencia.close();      
           } catch (SQLException ex) {
               System.out.println(ex);
           }  
          
    }//GEN-LAST:event_JB_MOSTRARActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
    }//GEN-LAST:event_formWindowOpened

    private void JB_REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_REGISTROActionPerformed
     IngresarUsuario From=new IngresarUsuario(); 
   From.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_JB_REGISTROActionPerformed

    private void JB_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ELIMINARActionPerformed
      String SQL;
        Statement Sentencia;
        SQL = "DELETE FROM HUMANO " + "WHERE ID = "+"" + TXT_MOSTRAR.getText()+"";
        try{
          System.out.print(SQL);
          Sentencia = PRINCIPAL_CONECCION.Conexion.createStatement();
          Sentencia.executeUpdate(SQL);
          JOptionPane.showMessageDialog(null, "Eliminado");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error:" + e.getMessage() );   
        }   
    }//GEN-LAST:event_JB_ELIMINARActionPerformed

    private void JT_TABLESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_TABLESMouseClicked
   int Fila = JT_TABLES.getSelectedRow();
        if (Fila <0) return;
        TXT_MOSTRAR.setText(JT_TABLES.getValueAt(Fila, 0).toString());
        
    }//GEN-LAST:event_JT_TABLESMouseClicked

    private void JB_EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EDITARActionPerformed
       IngresarUsuario datos =new IngresarUsuario();
       int Fila = JT_TABLES.getSelectedRow();
       if (Fila <0) return;
       IngresarUsuario.TXT_ID.setText(JT_TABLES.getValueAt(Fila, 0).toString());
       IngresarUsuario.TXT_NOMBRE.setText(JT_TABLES.getValueAt(Fila, 1).toString());
       IngresarUsuario.TXT_APELLIDO.setText(JT_TABLES.getValueAt(Fila, 2).toString());
       IngresarUsuario.TXT_PESO.setText(JT_TABLES.getValueAt(Fila, 3).toString());
       IngresarUsuario.JBC_SEXO.setSelectedItem(JT_TABLES.getValueAt(Fila, 4).toString());
       IngresarUsuario.JBC_DEPARTA.setSelectedItem(JT_TABLES.getValueAt(Fila, 5).toString());
       IngresarUsuario.JBC_MUNICIPIO.setSelectedItem(JT_TABLES.getValueAt(Fila, 6).toString());
       datos.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_JB_EDITARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_EDITAR;
    private javax.swing.JButton JB_ELIMINAR;
    private javax.swing.JButton JB_MOSTRAR;
    private javax.swing.JButton JB_REGISTRO;
    private javax.swing.JTable JT_TABLES;
    private javax.swing.JTextField TXT_MOSTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
